title: Notifications
description: The payload that configures notifications.
payload:
  payloadtype: com.apple.notificationsettings
  supportedOS:
    iOS:
      introduced: '9.3'
      multiple: false
      supervised: true
      allowmanualinstall: true
      sharedipad:
        mode: allowed
        devicechannel: true
        userchannel: true
      userenrollment:
        mode: forbidden
    macOS:
      introduced: '10.15'
      multiple: true
      devicechannel: true
      userchannel: true
      supervised: false
      requiresdep: false
      allowmanualinstall: true
      userenrollment:
        mode: forbidden
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  content: A notification settings payload specifies the restriction enforced notification
    settings for apps using their bundle identifier. The profile specifies notification
    settings by bundle identifier (even for apps that aren’t installed on the device
    yet), and those settings will always be enforced.
payloadkeys:
- key: NotificationSettings
  title: Notification settings
  type: <array>
  presence: required
  content: An array of notification settings dictionaries.
  subkeys:
  - key: NotificationSettingsItem
    title: Notification setting
    type: <dictionary>
    subkeys:
    - key: BundleIdentifier
      title: App bundle identifier
      type: <string>
      presence: required
      content: The bundle identifier of the app to which to apply these notification
        settings.
    - key: NotificationsEnabled
      title: Enable notifications
      type: <boolean>
      presence: optional
      default: true
      content: If `true`, enables notifications for this app.
    - key: ShowInNotificationCenter
      title: Show in Notification Center
      type: <boolean>
      presence: optional
      default: true
      content: If `true`, enables notifications in the Notification Center for this
        app.
    - key: ShowInLockScreen
      title: Show in Lock Screen
      type: <boolean>
      presence: optional
      default: true
      content: If `true`, enables notifications on the Lock Screen for this app.
    - key: AlertType
      title: Alert type
      type: <integer>
      presence: optional
      rangelist:
      - 0
      - 1
      - 2
      default: 1
      content: |-
        The type of alert for notifications for this app:

        - `0`: None
        - `1`: Temporary Banner
        - `2`: Persistent Banner
    - key: BadgesEnabled
      title: Badges enabled
      type: <boolean>
      presence: optional
      default: true
      content: If `true`, enables badges for this app.
    - key: SoundsEnabled
      title: Sounds enabled
      type: <boolean>
      presence: optional
      default: true
      content: If `true`, enables sounds for this app.
    - key: ShowInCarPlay
      title: Show in CarPlay
      supportedOS:
        iOS:
          introduced: '12.0'
        macOS:
          introduced: n/a
      type: <boolean>
      presence: optional
      default: true
      content: If `true`, enables notifications in CarPlay for this app.
    - key: CriticalAlertEnabled
      title: Critical alert enabled
      supportedOS:
        iOS:
          introduced: '12.0'
      type: <boolean>
      presence: optional
      default: false
      content: If `true`, enables critical alerts that can ignore Do Not Disturb and
        ringer settings for this app.
    - key: GroupingType
      title: Grouping type
      supportedOS:
        iOS:
          introduced: '12.0'
        macOS:
          introduced: n/a
      type: <integer>
      presence: optional
      rangelist:
      - 0
      - 1
      - 2
      default: 0
      content: |-
        The type of grouping for notifications for this app:

        - `0`: Automatic: Group notifications into app-specified groups.
        - `1`: By app: Group notifications into one group.
        - `2`: Off: Don't group notifications.
    - key: PreviewType
      title: Preview type
      supportedOS:
        iOS:
          introduced: '14.0'
        macOS:
          introduced: n/a
      type: <integer>
      presence: optional
      rangelist:
      - 0
      - 1
      - 2
      content: |-
        The type previews for notifications. This key overrides the value at Settings>Notifications>Show Previews.

        - `0` - Always: The device shows previews when locked and unlocked
        - `1` - When Unlocked: The device shows previews only when unlocked
        - `2` - Never: The device never shows previews
examples:
- title: Profile example
  files:
  - file: examples/mdm/profiles/com.apple.notificationsettings/example1.plist
