title: Remove Application Command
description: Remove an app.
payload:
  requesttype: RemoveApplication
  supportedOS:
    iOS:
      introduced: '5.0'
      accessrights: AllowAppInstallation
      supervised: false
      requiresdep: false
      sharedipad:
        mode: allowed
        devicechannel: true
        userchannel: false
      userenrollment:
        mode: allowed
    macOS:
      introduced: '11.0'
      accessrights: AllowAppInstallation
      devicechannel: true
      userchannel: false
      supervised: false
      requiresdep: false
      userenrollment:
        mode: allowed
    tvOS:
      introduced: '10.2'
      accessrights: AllowAppInstallation
      supervised: false
    visionOS:
      introduced: '1.1'
      accessrights: AllowAppInstallation
      supervised: false
      requiresdep: false
      userenrollment:
        mode: allowed
    watchOS:
      introduced: '10.0'
      accessrights: AllowAppInstallation
      supervised: false
payloadkeys:
- key: Identifier
  type: <string>
  presence: required
  content: |-
    The bundle identifier of the managed app.

    > Important:
    > For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone the watch pairs with. Obtain the watch's bundle identifier for an app with a watch bundle, in the `watchBundleId` key that's part of the Content Metadata query. For more information on this query, see `Getting app and book information (Legacy)`.
notes:
- title: ''
  content: |-
    This command allows a server to remove managed apps. It also allows a server to remove unmanaged and system deletable apps on supervised devices in iOS 26 and later, tvOS 26 and later, visionOS 26 and later, and watchOS 26 and later. When the device removes an app, it also removes the data for the app.

    This command fails for apps that Declarative Device Management is managing.

    Refer to the following sections to determine supported channels and requirements, and to see an example request and response.
examples:
  title: Example request and response
  files:
  - request-file: examples/mdm/commands/application.remove/example1.plist
    response-file: examples/mdm/commands/application.remove/example2.plist
