title: Invite To Program Command
description: Invite a user to join the Volume Purchase Program (VPP).
payload:
  requesttype: InviteToProgram
  supportedOS:
    iOS:
      introduced: '7.0'
      accessrights: AllowAppInstallation
      supervised: false
      requiresdep: false
      sharedipad:
        mode: allowed
        devicechannel: false
        userchannel: true
      userenrollment:
        mode: forbidden
    macOS:
      introduced: '10.9'
      accessrights: None
      devicechannel: false
      userchannel: true
      supervised: false
      requiresdep: false
      userenrollment:
        mode: forbidden
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
payloadkeys:
- key: ProgramID
  type: <string>
  presence: required
  rangelist:
  - com.apple.cloudvpp
  content: The program's identifier, which can only be `com.apple.cloudvpp`.
- key: InvitationURL
  type: <string>
  presence: required
  content: The Volume Purchase Program (VPP) invitation URL.
responsekeys:
- key: InvitationResult
  type: <string>
  presence: required
  rangelist:
  - Acknowledged
  - InvalidProgramID
  - InvalidInvitationURL
  content: The result of the command.
notes:
- title: ''
  content: |-
    This command allows a server to invite a user to join the Volume Purchase Program (VPP). It issues the invitation, but doesn't allow the server to monitor whether the user joins the program. This command yields a `NotNow` status if Setup Assistant is running.

    The command doesn't work with Account Driven enrollments.

    Refer to the following sections to determine supported channels and requirements, and to see an example request and response.
examples:
- title: Example request and response
  files:
  - request-file: examples/mdm/commands/application.invitetoprogram/example1.plist
    response-file: examples/mdm/commands/application.invitetoprogram/example2.plist
