title: Device Configured Command
description: Inform the device that it can allow the user to continue in Setup Assistant.
payload:
  requesttype: DeviceConfigured
  supportedOS:
    iOS:
      introduced: '9.0'
      accessrights: None
      supervised: true
      requiresdep: true
      sharedipad:
        mode: allowed
        devicechannel: true
        userchannel: false
      userenrollment:
        mode: forbidden
    macOS:
      introduced: '10.11'
      accessrights: None
      devicechannel: true
      userchannel: false
      supervised: false
      requiresdep: true
      userenrollment:
        mode: forbidden
    tvOS:
      introduced: '10.2'
      accessrights: None
      supervised: true
    visionOS:
      introduced: '2.0'
      accessrights: None
      supervised: true
      requiresdep: true
      userenrollment:
        mode: forbidden
    watchOS:
      introduced: n/a
  content: Informs the device that it can continue past DEP enrollment. Only works
    on devices in DEP that have their cloud configuration set to await configuration.
notes:
- title: ''
  content: |-
    This command only works on Device Enrollment Program (DEP) devices that have their cloud configuration set to await configuration.

    Refer to the following sections to determine supported channels and requirements, and to see an example request and response.
