title: Managed Application Feedback Command
description: Get app feedback from a managed app on the device.
payload:
  requesttype: ManagedApplicationFeedback
  supportedOS:
    iOS:
      introduced: '7.0'
      accessrights: AllowAppInstallation
      supervised: false
      requiresdep: false
      sharedipad:
        mode: allowed
        devicechannel: true
        userchannel: false
      userenrollment:
        mode: allowed
    macOS:
      introduced: '11.0'
      accessrights: AllowAppInstallation
      devicechannel: false
      userchannel: true
      userenrollment:
        mode: allowed
    tvOS:
      introduced: '10.2'
      accessrights: AllowAppInstallation
      supervised: false
    visionOS:
      introduced: '1.1'
      accessrights: AllowAppInstallation
      supervised: false
      requiresdep: false
      userenrollment:
        mode: allowed
    watchOS:
      introduced: n/a
payloadkeys:
- key: Identifiers
  type: <array>
  presence: required
  content: The bundle identifiers of the managed apps.
  subkeys:
  - key: IdentifiersItem
    type: <string>
- key: DeleteFeedback
  type: <boolean>
  presence: optional
  default: false
  content: If `true`, delete the app's feedback dictionary after the server reads
    it. Apps that are managed by Declarative Device Management are ignored.
responsekeys:
- key: ManagedApplicationFeedback
  type: <array>
  presence: required
  content: An array of managed app feedback items.
  subkeys:
  - key: ManagedApplicationFeedbackItem
    type: <dictionary>
    content: A dictionary that contains a managed app's feedback item.
    subkeys:
    - key: Identifier
      type: <string>
      presence: required
      content: The app's bundle identifier.
    - key: Feedback
      type: <dictionary>
      presence: optional
      content: The app's feedback.
      subkeys:
      - key: ANY
        type: <any>
        presence: optional
        content: The app's feedback items.
notes:
- title: ''
  content: |-
    This command allows the server to get the feedback information of managed apps. In macOS 12 and later, macOS supports this command on the user channel.

    The response doesn't include apps that Declarative Device Management is managing.

    Refer to the following sections to determine supported channels and requirements, and to see an example request and response.
examples:
- title: Example request and response
  files:
  - request-file: examples/mdm/commands/managed.application.feedback/example1.plist
    response-file: examples/mdm/commands/managed.application.feedback/example2.plist
