title: Services Configuration Files
description: Specifies managed configuration files for services
payload:
  declarationtype: com.apple.configuration.services.configuration-files
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: '14.0'
      allowed-enrollments:
      - device
      allowed-scopes:
      - system
    tvOS:
      introduced: n/a
    watchOS:
      introduced: n/a
payloadkeys:
- key: ServiceType
  title: Service Type
  type: <string>
  presence: required
  content: |-
    The identifier of the system service whose managed configuration files are being specified.
    This should be a reverse DNS style identifier. The "com.apple." prefix is reserved for built-in services.
    The available built-in services are:
    * com.apple.sshd - configures sshd
    * com.apple.sudo - configures sudo
    * com.apple.pam - configures PAM
    * com.apple.cups - configures CUPS
    * com.apple.apache.httpd - configures Apache httpd
    * com.apple.bash - configures bash
    * com.apple.zsh - configures zsh
- key: DataAssetReference
  title: Data Asset Reference
  type: <string>
  presence: required
  content: Specifies the identifier of an asset declaration containing a reference
    to the files to be used for the system service configuration. The corresponding
    asset must be of type "com.apple.asset.data". The referenced data must be a zip
    archive of an entire directory, that will be expanded and stored in a well known
    location for the system service. The asset's "ContentType" and "Hash-SHA-256"
    keys in the "Reference" key are required.
